// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupScreen():Promise<string>;

export function OnCreateAccountClicked():Promise<void>;
