// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupScreen() {
  return window['go']['main']['App']['GetStartupScreen']();
}

export function OnCreateAccountClicked() {
  return window['go']['main']['App']['OnCreateAccountClicked']();
}
